In [9]:
import numpy as np
calls=np.array([5,6,7,8,3])
print(calls)
print(calls.shape)

[5 6 7 8 3]
(5,)


multi_dimention Array


In [ ]:
dimension=np.array((['Jan','Feb','Mar'],
                   [300,400,500],
                   [600,700,800],
                   [50,30,200]))
Sum=np.sum(dimension)
print(Sum)
print(dimension.shape)
print(dimension)
print(dimension[2][2])
print(dimension[1,:])
print(dimension[:,1])

TypeError: the resolved dtypes are not compatible with add.reduce. Resolved (dtype('<U21'), dtype('<U21'), dtype('<U42'))

Index Array


In [ ]:
print(dimension[2][2])
print(dimension[1,:])
print(dimension[:,1])
print(dimension[1:,2])
print(dimension[1:,1])
print(dimension[1:,])

800
['300' '400' '500']
['Feb' '400' '700' '30']
['400' '700' '30']


In [24]:
#statisfaction Rating
sr=np.array([3.6,4,2,3,1,7,9])

srr=(sr>=2) & (sr<=4)
print(srr)

[ True  True  True  True False False False]


In [ ]:
dimension=np.array((
                   [300,400,500],
                   [600,700,800],
                   [50,30,200]))
print(sum(dimension))





[ 950 1130 1500]


In [ ]:
dimension=np.array((['Jan','Feb','Mar'],
                   [300,400,500],
                   [600,700,800],
                   [50,30,200]))
Sum=np.sum(dimension[1:,:].astype('int'))
print(Sum)
Mean=np.mean(dimension[1:,:].astype('int'))
print(Mean)

2380
396.6666666666667


In [46]:
North=np.array([5,100,30])
South=np.array([3,2,5])

Merge=np.concatenate((North,South))

print(Merge)


[  5 100  30   3   2   5]


In [8]:
import numpy as np
Duration=np.array([119,68,128,49])
print(np.where(Duration==199))
Duration[(np.where(Duration==199))]


(array([], dtype=int64),)


array([], dtype=int64)

Highest rate customers

In [27]:
rating=np.array([2,3,4.5,2,6])
C_id=np.array(['c101','c102','c103','c104'])
print(np.where(C_id=='c103'))
print(rating[np.where(C_id=='c103')])
print(np.sort(rating)[::-1])
print(np.max(rating))
print(C_id[np.where(rating==4.5)])




(array([2]),)
[4.5]
[6.  4.5 3.  2.  2. ]
6.0
['c103']


In [ ]:
duration=np.array([123,45,67,89,34])
print(np.average(duration))
satisfaction=np.array([5,4,3,5,2,4,5,3])
print(np.sort(satisfaction)[::-1])
print(np.max(satisfaction))

calls=np.array([120,130,160,180,170,140,200])

print(calls[np.where(calls>150)])

print(np.sort(duration))
print(satisfaction[np.where(satisfaction==5)])

print()

71.6
[5 5 5 4 4 3 3 2]
5
[160 180 170 200]
[ 34  45  67  89 123]
[5 5 5]
